//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessibleSample.ResX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccessibleSample.ResX.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessible Controls.
        /// </summary>
        internal static string AccessibleControls {
            get {
                return ResourceManager.GetString("AccessibleControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessible Sample.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Dot.
        /// </summary>
        internal static string FestivalFirst {
            get {
                return ResourceManager.GetString("FestivalFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festivals.
        /// </summary>
        internal static string Festivals {
            get {
                return ResourceManager.GetString("Festivals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewind North.
        /// </summary>
        internal static string FestivalSecond {
            get {
                return ResourceManager.GetString("FestivalSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inaccessible Controls.
        /// </summary>
        internal static string InaccessibleControls {
            get {
                return ResourceManager.GetString("InaccessibleControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not available.
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button and Item Accessibility.
        /// </summary>
        internal static string PageHeading {
            get {
                return ResourceManager.GetString("PageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample app demonstrates some fundamental steps relating to building .NET MAUI apps that are more accessible to more people..
        /// </summary>
        internal static string PageSubheading {
            get {
                return ResourceManager.GetString("PageSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Button Clicked..
        /// </summary>
        internal static string PlayButtonClicked {
            get {
                return ResourceManager.GetString("PlayButtonClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit the app ReadMe at Github.
        /// </summary>
        internal static string ReadMeButtonLabel {
            get {
                return ResourceManager.GetString("ReadMeButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        internal static string SampleItemSongAccessibleNotAvailableFormat {
            get {
                return ResourceManager.GetString("SampleItemSongAccessibleNotAvailableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here Comes the Sun.
        /// </summary>
        internal static string SongFirst {
            get {
                return ResourceManager.GetString("SongFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        internal static string Songs {
            get {
                return ResourceManager.GetString("Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell the Bees.
        /// </summary>
        internal static string SongSecond {
            get {
                return ResourceManager.GetString("SongSecond", resourceCulture);
            }
        }
    }
}
